services:
  - type: web
    name: cinema-list-derby
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cinema-list-derby-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: TMDB_API_KEY
        sync: false

databases:
  - name: cinema-list-derby-db
    databaseName: cinema_list_derby_production
    user: cinema_list_derby

